@startuml
title MD de UB Cultura

object UBCultura
object Material {
       codi
       titol
       autor
}

object Llibre {
       pagines
}
object Disc{
       discografica
}
object ExemplarLlibre {

}
object ExemplarDisc{

}
object Exemplar {
	codiExemplar
}
object Client{
       DNI
       nom
}
object Prestec {
       dataInici
       dataFi
}
object Direccio


UBCultura “1”*-up--"1..* llistaMat" Material: Disposa
UBCultura “1”*-left-“llistaCli *" Client: Té
Material  <|-left- Llibre
Material <|-- Disc

Exemplar <|-right- ExemplarLlibre
Exemplar <|-- ExemplarDisc


ExemplarLlibre “*” -right- “1” Llibre: EstàDescritPer
ExemplarDisc “*” -right- “1” Disc: EstàDescritPer

Client "1..*" -left- "1" Direccio: Té
Client "1 cli" -- " llistaPeti 0..5" Prestec: Demana
Prestec “1” -- “1” Exemplar: Reserva

@enduml